#version: '3'

services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_NODE_TYPE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    volumes:
      - ./data:/data
      - spark-data:/opt/spark-data  # Volume pour persister /opt/spark-data
    networks:
      - spark-network
    command: >
      sh -c "mkdir -p /opt/spark-data
      && cp /data/test_spark.py /opt/spark-data/
      && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"  # Adaptez la commande Spark

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_NODE_TYPE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
    networks:
      - spark-network

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_NODE_TYPE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - ./data:/data
    networks:
      - spark-network


  spark-worker-3:
    build: .
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    environment:
      - SPARK_NODE_TYPE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8083
    ports:
      - "8083:8083"
    volumes:
      - ./data:/data
    networks:
      - spark-network


  spark-worker-4:
    build: .
    container_name: spark-worker-4
    hostname: spark-worker-4
    depends_on:
      - spark-master
    environment:
      - SPARK_NODE_TYPE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8084
    ports:
      - "8084:8084"
    volumes:
      - ./data:/data
    networks:
      - spark-network

volumes:   #volume automatique
  spark-data:

networks:
  spark-network:
    driver: bridge